services:

  db:
    build:
      context: ./dbserver
      dockerfile: Dockerfile.alpine

    container_name: 17017615_cyberdelia_db_c

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: gibson
    secrets:
      - db_user
      - db_password

    volumes:
      - db_data:/var/lib/postgresql/data

    networks:
      - cyberdelia

    expose:
      - "5432"

    security_opt:
      - no-new-privileges:true

    cap_drop:
      - ALL

    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE

    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 512M


  web:
    build:
      context: ./webserver
      dockerfile: Dockerfile.alpine

    container_name: 17017615_cyberdelia_web_c

    restart: unless-stopped

    user: "20615:20615"

    depends_on:
      - db

    environment:
      DB_HOST: db
      DB_NAME: gibson
      DB_USER_FILE: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_password

    secrets:
      - db_user
      - db_password

    ports:
      - "80:80"

    expose:
      - "8015"

    networks:
      - cyberdelia

    read_only: true

    tmpfs:
      - /tmp
      - /run/nginx:uid=20615,gid=20615,mode=0755
      - /var/log/nginx:uid=20615,gid=20615,mode=0755
      - /var/lib/nginx/tmp:uid=20615,gid=20615,mode=0755

    security_opt:
      - no-new-privileges:true

    cap_drop:
      - ALL

    cap_add:
      - NET_BIND_SERVICE

    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M


networks:
  cyberdelia:
    driver: bridge


volumes:
  db_data:


secrets:
  db_user:
    file: ./secrets/db_user.txt

  db_password:
    file: ./secrets/db_password.txt
