# CYBERDELIA hardened PostgreSQL configuration

listen_addresses = '*'
port = 5432

max_connections = 100

password_encryption = scram-sha-256

hba_file = '/etc/postgresql/pg_hba.conf'

logging_collector = off
