# CYBERDELIA hardened PostgreSQL authentication

# Local Unix socket connections
local   all             all                             scram-sha-256

# IPv4 Docker network connections
host    all             all             0.0.0.0/0       scram-sha-256

# IPv6 Docker network connections
host    all             all             ::/0            scram-sha-256
