name: CYBERDELIA Security Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  container-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t cyberdelia-secure ./webserver

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: cyberdelia-secure
          format: table
          output: trivy-report.txt
          exit-code: 0
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-security-report
          path: trivy-report.txt
